language: python

services:
  - postgresql

python:
  - "3.4"
  - "2.7"

env:
  - DJANGO="django==1.7.7"
  - DJANGO="django==1.6.11"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install $DJANGO
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls --use-mirrors
  - python setup.py -q install

before_script:
  - psql template1 -c 'create extension hstore;'
  - createdb drf_hstore

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source rest_framework_hstore manage.py test

after_success:
  coveralls
